language: php
php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly
matrix:
    allow_failures:
        - php: 7.4
        - php: nightly
    fast_finish: true
install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update
    - sudo apt-get install g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
    - wget https://github.com/apiaryio/drafter/releases/download/v3.2.6/drafter-v3.2.6.tar.gz
    - tar -xzvf drafter-v3.2.6.tar.gz
    - pushd drafter-v3.2.6 && ./configure && make && sudo make install && popd
before_script:
    - composer self-update
    - composer install --dev
script:
    - composer test
after_success:
    - php vendor/bin/coveralls --verbose
